nelmio_api_doc:
    documentation:
        info:
            title: Code & Conquest API
            description: The API for the Netrunner code-challenge game.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Expose all routes starting with /api, except for the documentation route itself.